package com.projetBMDrive.entities;
// Generated 28 juin 2021 � 16:47:16 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * BmdArticle generated by hbm2java
 */
@Entity
@Table(name = "BMD_ARTICLE", schema = "BMDRIVE")
public class BmdArticle implements java.io.Serializable {

	private BigDecimal artId;
	private String artAuteur;
	private String artCote;
	private String artTitre;
	private Set<BmdSupportmedia> bmdSupportmedias = new HashSet<BmdSupportmedia>(0);
	private Set<BmdLivre> bmdLivres = new HashSet<BmdLivre>(0);

	public BmdArticle() {
	}

	public BmdArticle(BigDecimal artId, String artAuteur, String artCote, String artTitre) {
		this.artId = artId;
		this.artAuteur = artAuteur;
		this.artCote = artCote;
		this.artTitre = artTitre;
	}

	public BmdArticle(BigDecimal artId, String artAuteur, String artCote, String artTitre,
			Set<BmdSupportmedia> bmdSupportmedias, Set<BmdLivre> bmdLivres) {
		this.artId = artId;
		this.artAuteur = artAuteur;
		this.artCote = artCote;
		this.artTitre = artTitre;
		this.bmdSupportmedias = bmdSupportmedias;
		this.bmdLivres = bmdLivres;
	}

	@Id
	@SequenceGenerator(name="BMD_ARTICLE_SEQ", sequenceName = "BMD_ARTICLE_SEQ", allocationSize = 1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="BMD_ARTICLE_SEQ")
	@Column(name = "ART_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getArtId() {
		return this.artId;
	}

	public void setArtId(BigDecimal artId) {
		this.artId = artId;
	}

	@Column(name = "ART_AUTEUR", nullable = false, length = 400)
	public String getArtAuteur() {
		return this.artAuteur;
	}

	public void setArtAuteur(String artAuteur) {
		this.artAuteur = artAuteur;
	}

	@Column(name = "ART_COTE", nullable = false, length = 80)
	public String getArtCote() {
		return this.artCote;
	}

	public void setArtCote(String artCote) {
		this.artCote = artCote;
	}

	@Column(name = "ART_TITRE", nullable = false, length = 400)
	public String getArtTitre() {
		return this.artTitre;
	}

	public void setArtTitre(String artTitre) {
		this.artTitre = artTitre;
	}
	
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bmdArticle")
	public Set<BmdSupportmedia> getBmdSupportmedias() {
		return this.bmdSupportmedias;
	}

	public void setBmdSupportmedias(Set<BmdSupportmedia> bmdSupportmedias) {
		this.bmdSupportmedias = bmdSupportmedias;
	}
	
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bmdArticle")
	public Set<BmdLivre> getBmdLivres() {
		return this.bmdLivres;
	}

	public void setBmdLivres(Set<BmdLivre> bmdLivres) {
		this.bmdLivres = bmdLivres;
	}

}
