package com.projetBMDrive.entities;
// Generated 17 juin 2021 � 10:20:52 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * BmdAdherent generated by hbm2java
 */
@Entity
@Table(name = "BMD_ADHERENT", schema = "BMDRIVE")
public class BmdAdherent implements java.io.Serializable {

	private BigDecimal adhId;
	private BmdIdentite bmdIdentite;
	private BmdPanier bmdPanier;
	private String adhNomUtilisateur;
	private String adhMotDePasse;

	public BmdAdherent() {
	}

	public BmdAdherent(BigDecimal adhId) {
		this.adhId = adhId;
	}

	public BmdAdherent(BigDecimal adhId, BmdIdentite bmdIdentite, BmdPanier bmdPanier, String adhNomUtilisateur,
			String adhMotDePasse) {
		this.adhId = adhId;
		this.bmdIdentite = bmdIdentite;
		this.bmdPanier = bmdPanier;
		this.adhNomUtilisateur = adhNomUtilisateur;
		this.adhMotDePasse = adhMotDePasse;
	}

	@Id
	@SequenceGenerator(name="BMD_ADHERENT_SEQ", sequenceName = "BMD_ADHERENT_SEQ", allocationSize = 1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="BMD_ADHERENT_SEQ")
	@Column(name = "ADH_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getAdhId() {
		return this.adhId;
	}

	public void setAdhId(BigDecimal adhId) {
		this.adhId = adhId;
	}

	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ADH_ID_IDENTITE")
	public BmdIdentite getBmdIdentite() {
		return this.bmdIdentite;
	}

	public void setBmdIdentite(BmdIdentite bmdIdentite) {
		this.bmdIdentite = bmdIdentite;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ADH_ID_PANIER")
	public BmdPanier getBmdPanier() {
		return this.bmdPanier;
	}

	public void setBmdPanier(BmdPanier bmdPanier) {
		this.bmdPanier = bmdPanier;
	}

	@Column(name = "ADH_NOM_UTILISATEUR", length = 20)
	public String getAdhNomUtilisateur() {
		return this.adhNomUtilisateur;
	}

	public void setAdhNomUtilisateur(String adhNomUtilisateur) {
		this.adhNomUtilisateur = adhNomUtilisateur;
	}

	@Column(name = "ADH_MOT_DE_PASSE", length = 20)
	public String getAdhMotDePasse() {
		return this.adhMotDePasse;
	}

	public void setAdhMotDePasse(String adhMotDePasse) {
		this.adhMotDePasse = adhMotDePasse;
	}

}
