package com.projetBMDrive.entities;
// Generated 28 juin 2021 � 16:47:16 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * BmdCategorie generated by hbm2java
 */
@Entity
@Table(name = "BMD_CATEGORIE", schema = "BMDRIVE")
public class BmdCategorie implements java.io.Serializable {

	private BigDecimal catId;
	private BmdLivre bmdLivre;
	private BmdSupportmedia bmdSupportmedia;
	private String catLibelle;

	public BmdCategorie() {
	}

	public BmdCategorie(BigDecimal catId, String catLibelle) {
		this.catId = catId;
		this.catLibelle = catLibelle;
	}

	public BmdCategorie(BigDecimal catId, BmdLivre bmdLivre, BmdSupportmedia bmdSupportmedia, String catLibelle) {
		this.catId = catId;
		this.bmdLivre = bmdLivre;
		this.bmdSupportmedia = bmdSupportmedia;
		this.catLibelle = catLibelle;
	}

	@Id
	@SequenceGenerator(name="BMD_CATEGORIE_SEQ", sequenceName = "BMD_CATEGORIE_SEQ", allocationSize = 1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="BMD_CATEGORIE_SEQ")
	@Column(name = "CAT_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getCatId() {
		return this.catId;
	}

	public void setCatId(BigDecimal catId) {
		this.catId = catId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CAT_LIVRE_ID")
	public BmdLivre getBmdLivre() {
		return this.bmdLivre;
	}

	public void setBmdLivre(BmdLivre bmdLivre) {
		this.bmdLivre = bmdLivre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CAT_SUPMED_ID")
	public BmdSupportmedia getBmdSupportmedia() {
		return this.bmdSupportmedia;
	}

	public void setBmdSupportmedia(BmdSupportmedia bmdSupportmedia) {
		this.bmdSupportmedia = bmdSupportmedia;
	}

	@Column(name = "CAT_LIBELLE", nullable = false, length = 80)
	public String getCatLibelle() {
		return this.catLibelle;
	}

	public void setCatLibelle(String catLibelle) {
		this.catLibelle = catLibelle;
	}

}
