package com.projetBMDrive.entities;
// Generated 28 juin 2021 � 11:55:43 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * BmdCasier generated by hbm2java
 */
@Entity
@Table(name = "BMD_CASIER", schema = "BMDRIVE")
public class BmdCasier implements java.io.Serializable {

	private BigDecimal casId;
	private BmdReservation bmdReservation;
	private String casEtat;

	public BmdCasier() {
	}

	public BmdCasier(BigDecimal casId, String casEtat) {
		this.casId = casId;
		this.casEtat = casEtat;
	}

	public BmdCasier(BigDecimal casId, BmdReservation bmdReservation, String casEtat) {
		this.casId = casId;
		this.bmdReservation = bmdReservation;
		this.casEtat = casEtat;
	}

	@Id
	@SequenceGenerator(name="BMD_CASIER_SEQ", sequenceName = "BMD_CASIER_SEQ", allocationSize = 1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="BMD_CASIER_SEQ")
	@Column(name = "CAS_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getCasId() {
		return this.casId;
	}

	public void setCasId(BigDecimal casId) {
		this.casId = casId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CAS_ID_RES")
	public BmdReservation getBmdReservation() {
		return this.bmdReservation;
	}

	public void setBmdReservation(BmdReservation bmdReservation) {
		this.bmdReservation = bmdReservation;
	}

	@Column(name = "CAS_ETAT", nullable = false, length = 20)
	public String getCasEtat() {
		return this.casEtat;
	}

	public void setCasEtat(String casEtat) {
		this.casEtat = casEtat;
	}

}
