package com.projetBMDrive.entities;
// Generated 17 juin 2021 � 10:20:52 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BmdCategorie generated by hbm2java
 */
@Entity
@Table(name = "BMD_CATEGORIE", schema = "BMDRIVE")
public class BmdCategorie implements java.io.Serializable {

	private BigDecimal catId;
	private BmdArticle bmdArticle;
	private String catLibelle;

	public BmdCategorie() {
	}

	public BmdCategorie(BigDecimal catId, String catLibelle) {
		this.catId = catId;
		this.catLibelle = catLibelle;
	}

	public BmdCategorie(BigDecimal catId, BmdArticle bmdArticle, String catLibelle) {
		this.catId = catId;
		this.bmdArticle = bmdArticle;
		this.catLibelle = catLibelle;
	}

	@Id

	@Column(name = "CAT_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getCatId() {
		return this.catId;
	}

	public void setCatId(BigDecimal catId) {
		this.catId = catId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CAT_ARTICLE_ID")
	public BmdArticle getBmdArticle() {
		return this.bmdArticle;
	}

	public void setBmdArticle(BmdArticle bmdArticle) {
		this.bmdArticle = bmdArticle;
	}

	@Column(name = "CAT_LIBELLE", nullable = false, length = 20)
	public String getCatLibelle() {
		return this.catLibelle;
	}

	public void setCatLibelle(String catLibelle) {
		this.catLibelle = catLibelle;
	}

}
