package com.projetBMDrive.entities;
// Generated 29 juin 2021 � 14:18:41 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * BmdIdentite generated by hbm2java
 */
@Entity
@Table(name = "BMD_IDENTITE", schema = "BMDRIVE")
public class BmdIdentite implements java.io.Serializable {

	private BigDecimal ideId;
	private BmdAdresse bmdAdresse;
	private Date ideDateNaissance;
	private String ideJustificatifDomicile;
	private String ideJustificatifIdentite;
	private String ideMail;
	private String ideNom;
	private String idePrenom;
	private String ideSexe;
	private String ideTelephone;
	private BmdAdherent bmdAdherents;

	public BmdIdentite() {
	}

	public BmdIdentite(BigDecimal ideId, BmdAdresse bmdAdresse, Date ideDateNaissance, String ideJustificatifDomicile,
			String ideJustificatifIdentite, String ideMail, String ideNom, String idePrenom, String ideSexe,
			String ideTelephone) {
		this.ideId = ideId;
		this.bmdAdresse = bmdAdresse;
		this.ideDateNaissance = ideDateNaissance;
		this.ideJustificatifDomicile = ideJustificatifDomicile;
		this.ideJustificatifIdentite = ideJustificatifIdentite;
		this.ideMail = ideMail;
		this.ideNom = ideNom;
		this.idePrenom = idePrenom;
		this.ideSexe = ideSexe;
		this.ideTelephone = ideTelephone;
	}

	public BmdIdentite(BigDecimal ideId, BmdAdresse bmdAdresse, Date ideDateNaissance, String ideJustificatifDomicile,
			String ideJustificatifIdentite, String ideMail, String ideNom, String idePrenom, String ideSexe,
			String ideTelephone, BmdAdherent bmdAdherents) {
		this.ideId = ideId;
		this.bmdAdresse = bmdAdresse;
		this.ideDateNaissance = ideDateNaissance;
		this.ideJustificatifDomicile = ideJustificatifDomicile;
		this.ideJustificatifIdentite = ideJustificatifIdentite;
		this.ideMail = ideMail;
		this.ideNom = ideNom;
		this.idePrenom = idePrenom;
		this.ideSexe = ideSexe;
		this.ideTelephone = ideTelephone;
		this.bmdAdherents = bmdAdherents;
	}

	@Id
	//@SequenceGenerator(name="BMD_IDENTITE_SEQ", sequenceName = "BMD_IDENTITE_SEQ", allocationSize = 1)
    //@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="BMD_IDENTITE_SEQ")
	@Column(name = "IDE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdeId() {
		return this.ideId;
	}

	public void setIdeId(BigDecimal ideId) {
		this.ideId = ideId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "IDE_ADRESSE", nullable = false)
	public BmdAdresse getBmdAdresse() {
		return this.bmdAdresse;
	}

	public void setBmdAdresse(BmdAdresse bmdAdresse) {
		this.bmdAdresse = bmdAdresse;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IDE_DATE_NAISSANCE", nullable = false, length = 7)
	public Date getIdeDateNaissance() {
		return this.ideDateNaissance;
	}

	public void setIdeDateNaissance(Date ideDateNaissance) {
		this.ideDateNaissance = ideDateNaissance;
	}

	@Column(name = "IDE_JUSTIFICATIF_DOMICILE", nullable = false)
	public String getIdeJustificatifDomicile() {
		return this.ideJustificatifDomicile;
	}

	public void setIdeJustificatifDomicile(String ideJustificatifDomicile) {
		this.ideJustificatifDomicile = ideJustificatifDomicile;
	}

	@Column(name = "IDE_JUSTIFICATIF_IDENTITE", nullable = false)
	public String getIdeJustificatifIdentite() {
		return this.ideJustificatifIdentite;
	}

	public void setIdeJustificatifIdentite(String ideJustificatifIdentite) {
		this.ideJustificatifIdentite = ideJustificatifIdentite;
	}

	@Column(name = "IDE_MAIL", nullable = false, length = 1600)
	public String getIdeMail() {
		return this.ideMail;
	}

	public void setIdeMail(String ideMail) {
		this.ideMail = ideMail;
	}

	@Column(name = "IDE_NOM", nullable = false, length = 800)
	public String getIdeNom() {
		return this.ideNom;
	}

	public void setIdeNom(String ideNom) {
		this.ideNom = ideNom;
	}

	@Column(name = "IDE_PRENOM", nullable = false, length = 800)
	public String getIdePrenom() {
		return this.idePrenom;
	}

	public void setIdePrenom(String idePrenom) {
		this.idePrenom = idePrenom;
	}

	@Column(name = "IDE_SEXE", nullable = false, length = 16)
	public String getIdeSexe() {
		return this.ideSexe;
	}

	public void setIdeSexe(String ideSexe) {
		this.ideSexe = ideSexe;
	}

	@Column(name = "IDE_TELEPHONE", nullable = false, length = 320)
	public String getIdeTelephone() {
		return this.ideTelephone;
	}

	public void setIdeTelephone(String ideTelephone) {
		this.ideTelephone = ideTelephone;
	}

	@JsonIgnore
	@OneToOne(fetch = FetchType.EAGER, mappedBy = "bmdIdentite")
	public BmdAdherent getBmdAdherents() {
		return this.bmdAdherents;
	}

	public void setBmdAdherents(BmdAdherent bmdAdherents) {
		this.bmdAdherents = bmdAdherents;
	}

}
