package com.projetBMDrive.entities;
// Generated 28 juin 2021 � 16:47:16 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * BmdIdentite generated by hbm2java
 */
@Entity
@Table(name = "BMD_IDENTITE", schema = "BMDRIVE")
public class BmdIdentite implements java.io.Serializable {

	private BigDecimal ideId;
	private BmdAdresse bmdAdresse;
	private Date ideDateNaissance;
	private String ideMail;
	private String ideNom;
	private String idePrenom;
	private String ideSexe;
	private String ideTelephone;
	private Blob ideJustificatifIdentite;
	private Blob ideJustificatifDomicile;
	private Set<BmdVisiteur> bmdVisiteurs = new HashSet<BmdVisiteur>(0);
	private Set<BmdAdherent> bmdAdherents = new HashSet<BmdAdherent>(0);

	public BmdIdentite() {
	}

	public BmdIdentite(BigDecimal ideId, BmdAdresse bmdAdresse, Date ideDateNaissance, String ideMail, String ideNom,
			String idePrenom, String ideSexe, String ideTelephone, Blob ideJustificatifIdentite,
			Blob ideJustificatifDomicile) {
		this.ideId = ideId;
		this.bmdAdresse = bmdAdresse;
		this.ideDateNaissance = ideDateNaissance;
		this.ideMail = ideMail;
		this.ideNom = ideNom;
		this.idePrenom = idePrenom;
		this.ideSexe = ideSexe;
		this.ideTelephone = ideTelephone;
		this.ideJustificatifIdentite = ideJustificatifIdentite;
		this.ideJustificatifDomicile = ideJustificatifDomicile;
	}

	public BmdIdentite(BigDecimal ideId, BmdAdresse bmdAdresse, Date ideDateNaissance, String ideMail, String ideNom,
			String idePrenom, String ideSexe, String ideTelephone, Blob ideJustificatifIdentite,
			Blob ideJustificatifDomicile, Set<BmdVisiteur> bmdVisiteurs, Set<BmdAdherent> bmdAdherents) {
		this.ideId = ideId;
		this.bmdAdresse = bmdAdresse;
		this.ideDateNaissance = ideDateNaissance;
		this.ideMail = ideMail;
		this.ideNom = ideNom;
		this.idePrenom = idePrenom;
		this.ideSexe = ideSexe;
		this.ideTelephone = ideTelephone;
		this.ideJustificatifIdentite = ideJustificatifIdentite;
		this.ideJustificatifDomicile = ideJustificatifDomicile;
		this.bmdVisiteurs = bmdVisiteurs;
		this.bmdAdherents = bmdAdherents;
	}

	@Id
	@SequenceGenerator(name="BMD_IDENTITE_SEQ", sequenceName = "BMD_IDENTITE_SEQ", allocationSize = 1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="BMD_IDENTITE_SEQ")
	@Column(name = "IDE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdeId() {
		return this.ideId;
	}

	public void setIdeId(BigDecimal ideId) {
		this.ideId = ideId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "IDE_ADRESSE", nullable = false)
	public BmdAdresse getBmdAdresse() {
		return this.bmdAdresse;
	}

	public void setBmdAdresse(BmdAdresse bmdAdresse) {
		this.bmdAdresse = bmdAdresse;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IDE_DATE_NAISSANCE", nullable = false, length = 7)
	public Date getIdeDateNaissance() {
		return this.ideDateNaissance;
	}

	public void setIdeDateNaissance(Date ideDateNaissance) {
		this.ideDateNaissance = ideDateNaissance;
	}

	@Column(name = "IDE_MAIL", nullable = false, length = 400)
	public String getIdeMail() {
		return this.ideMail;
	}

	public void setIdeMail(String ideMail) {
		this.ideMail = ideMail;
	}

	@Column(name = "IDE_NOM", nullable = false, length = 200)
	public String getIdeNom() {
		return this.ideNom;
	}

	public void setIdeNom(String ideNom) {
		this.ideNom = ideNom;
	}

	@Column(name = "IDE_PRENOM", nullable = false, length = 200)
	public String getIdePrenom() {
		return this.idePrenom;
	}

	public void setIdePrenom(String idePrenom) {
		this.idePrenom = idePrenom;
	}

	@Column(name = "IDE_SEXE", nullable = false, length = 4)
	public String getIdeSexe() {
		return this.ideSexe;
	}

	public void setIdeSexe(String ideSexe) {
		this.ideSexe = ideSexe;
	}

	@Column(name = "IDE_TELEPHONE", nullable = false, length = 80)
	public String getIdeTelephone() {
		return this.ideTelephone;
	}

	public void setIdeTelephone(String ideTelephone) {
		this.ideTelephone = ideTelephone;
	}

	@Column(name = "IDE_JUSTIFICATIF_IDENTITE", nullable = false)
	public Blob getIdeJustificatifIdentite() {
		return this.ideJustificatifIdentite;
	}

	public void setIdeJustificatifIdentite(Blob ideJustificatifIdentite) {
		this.ideJustificatifIdentite = ideJustificatifIdentite;
	}

	@Column(name = "IDE_JUSTIFICATIF_DOMICILE", nullable = false)
	public Blob getIdeJustificatifDomicile() {
		return this.ideJustificatifDomicile;
	}

	public void setIdeJustificatifDomicile(Blob ideJustificatifDomicile) {
		this.ideJustificatifDomicile = ideJustificatifDomicile;
	}
	
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bmdIdentite")
	public Set<BmdVisiteur> getBmdVisiteurs() {
		return this.bmdVisiteurs;
	}

	public void setBmdVisiteurs(Set<BmdVisiteur> bmdVisiteurs) {
		this.bmdVisiteurs = bmdVisiteurs;
	}
	
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bmdIdentite")
	public Set<BmdAdherent> getBmdAdherents() {
		return this.bmdAdherents;
	}

	public void setBmdAdherents(Set<BmdAdherent> bmdAdherents) {
		this.bmdAdherents = bmdAdherents;
	}

}
