package com.projetBMDrive.entities;
// Generated 29 juin 2021 � 14:18:41 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * BmdLivre generated by hbm2java
 */
@Entity
@Table(name = "BMD_LIVRE", schema = "BMDRIVE")
public class BmdLivre implements java.io.Serializable {

	private BigDecimal livId;
	private BmdArticle bmdArticle;
	private BmdCategorie bmdCategorie;
	private BmdPanier bmdPanier;

	public BmdLivre() {
	}

	public BmdLivre(BigDecimal livId, BmdArticle bmdArticle, BmdCategorie bmdCategorie) {
		this.livId = livId;
		this.bmdArticle = bmdArticle;
		this.bmdCategorie = bmdCategorie;
	}

	public BmdLivre(BigDecimal livId, BmdArticle bmdArticle, BmdCategorie bmdCategorie, BmdPanier bmdPanier) {
		this.livId = livId;
		this.bmdArticle = bmdArticle;
		this.bmdCategorie = bmdCategorie;
		this.bmdPanier = bmdPanier;
	}

	@Id
	//@SequenceGenerator(name="BMD_LIVRE_SEQ", sequenceName = "BMD_LIVRE_SEQ", allocationSize = 1)
    //@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="BMD_LIVRE_SEQ")
	@Column(name = "LIV_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getLivId() {
		return this.livId;
	}

	public void setLivId(BigDecimal livId) {
		this.livId = livId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "LIV_ARTICLE_ID", nullable = false)
	public BmdArticle getBmdArticle() {
		return this.bmdArticle;
	}

	public void setBmdArticle(BmdArticle bmdArticle) {
		this.bmdArticle = bmdArticle;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "LIV_CAT_ID", nullable = false)
	public BmdCategorie getBmdCategorie() {
		return this.bmdCategorie;
	}

	public void setBmdCategorie(BmdCategorie bmdCategorie) {
		this.bmdCategorie = bmdCategorie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LIV_PAN_ID")
	public BmdPanier getBmdPanier() {
		return this.bmdPanier;
	}

	public void setBmdPanier(BmdPanier bmdPanier) {
		this.bmdPanier = bmdPanier;
	}

}
