package com.projetBMDrive.entities;
// Generated 28 juin 2021 � 16:47:16 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * BmdLivre generated by hbm2java
 */
@Entity
@Table(name = "BMD_LIVRE", schema = "BMDRIVE")
public class BmdLivre implements java.io.Serializable {

	private BigDecimal livId;
	private BmdArticle bmdArticle;
	private Set<BmdPanier> bmdPaniers = new HashSet<BmdPanier>(0);
	private Set<BmdCategorie> bmdCategories = new HashSet<BmdCategorie>(0);

	public BmdLivre() {
	}

	public BmdLivre(BigDecimal livId, BmdArticle bmdArticle) {
		this.livId = livId;
		this.bmdArticle = bmdArticle;
	}

	public BmdLivre(BigDecimal livId, BmdArticle bmdArticle, Set<BmdPanier> bmdPaniers,
			Set<BmdCategorie> bmdCategories) {
		this.livId = livId;
		this.bmdArticle = bmdArticle;
		this.bmdPaniers = bmdPaniers;
		this.bmdCategories = bmdCategories;
	}

	@Id
	@SequenceGenerator(name="BMD_LIVRE_SEQ", sequenceName = "BMD_LIVRE_SEQ", allocationSize = 1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="BMD_LIVRE_SEQ")
	@Column(name = "LIV_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getLivId() {
		return this.livId;
	}

	public void setLivId(BigDecimal livId) {
		this.livId = livId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LIV_ARTICLE_ID", nullable = false)
	public BmdArticle getBmdArticle() {
		return this.bmdArticle;
	}

	public void setBmdArticle(BmdArticle bmdArticle) {
		this.bmdArticle = bmdArticle;
	}
	
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bmdLivre")
	public Set<BmdPanier> getBmdPaniers() {
		return this.bmdPaniers;
	}

	public void setBmdPaniers(Set<BmdPanier> bmdPaniers) {
		this.bmdPaniers = bmdPaniers;
	}
	
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bmdLivre")
	public Set<BmdCategorie> getBmdCategories() {
		return this.bmdCategories;
	}

	public void setBmdCategories(Set<BmdCategorie> bmdCategories) {
		this.bmdCategories = bmdCategories;
	}

}
