package com.projetBMDrive.entities;
// Generated 17 juin 2021 � 10:20:52 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BmdLivre generated by hbm2java
 */
@Entity
@Table(name = "BMD_LIVRE", schema = "BMDRIVE")
public class BmdLivre implements java.io.Serializable {

	private BigDecimal livId;
	private BmdArticle bmdArticle;
	private BigDecimal livNbPages;

	public BmdLivre() {
	}

	public BmdLivre(BigDecimal livId, BmdArticle bmdArticle, BigDecimal livNbPages) {
		this.livId = livId;
		this.bmdArticle = bmdArticle;
		this.livNbPages = livNbPages;
	}

	@Id

	@Column(name = "LIV_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getLivId() {
		return this.livId;
	}

	public void setLivId(BigDecimal livId) {
		this.livId = livId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LIV_ARTICLE_ID", nullable = false)
	public BmdArticle getBmdArticle() {
		return this.bmdArticle;
	}

	public void setBmdArticle(BmdArticle bmdArticle) {
		this.bmdArticle = bmdArticle;
	}

	@Column(name = "LIV_NB_PAGES", nullable = false, precision = 22, scale = 0)
	public BigDecimal getLivNbPages() {
		return this.livNbPages;
	}

	public void setLivNbPages(BigDecimal livNbPages) {
		this.livNbPages = livNbPages;
	}

}
