package com.projetBMDrive.entities;
// Generated 29 juin 2021 � 14:18:41 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * BmdPanier generated by hbm2java
 */
@Entity
@Table(name = "BMD_PANIER", schema = "BMDRIVE")
public class BmdPanier implements java.io.Serializable {

	private BigDecimal panId;
	private BmdAdherent bmdAdherent;
	private Date panDateEmprunt;
	private Date panDateRetour;
	private BmdReservation bmdReservations;
	private Set<BmdSupportmedia> bmdSupportmedias = new HashSet<BmdSupportmedia>(0);
	private Set<BmdLivre> bmdLivres = new HashSet<BmdLivre>(0);

	public BmdPanier() {
	}

	public BmdPanier(BigDecimal panId) {
		this.panId = panId;
	}

	public BmdPanier(BigDecimal panId, BmdAdherent bmdAdherent, Date panDateEmprunt, Date panDateRetour,
			Set<BmdSupportmedia> bmdSupportmedias, BmdReservation bmdReservations, Set<BmdLivre> bmdLivres) {
		this.panId = panId;
		this.bmdAdherent = bmdAdherent;
		this.panDateEmprunt = panDateEmprunt;
		this.panDateRetour = panDateRetour;
		this.bmdSupportmedias = bmdSupportmedias;
		this.bmdReservations = bmdReservations;
		this.bmdLivres = bmdLivres;
	}

	@Id
	@SequenceGenerator(name="BMD_PANIER_SEQ", sequenceName = "BMD_PANIER_SEQ", allocationSize = 1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="BMD_PANIER_SEQ")
	@Column(name = "PAN_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getPanId() {
		return this.panId;
	}

	public void setPanId(BigDecimal panId) {
		this.panId = panId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PAN_ID_ADH")
	public BmdAdherent getBmdAdherent() {
		return this.bmdAdherent;
	}

	public void setBmdAdherent(BmdAdherent bmdAdherent) {
		this.bmdAdherent = bmdAdherent;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PAN_DATE_EMPRUNT", length = 7)
	public Date getPanDateEmprunt() {
		return this.panDateEmprunt;
	}

	public void setPanDateEmprunt(Date panDateEmprunt) {
		this.panDateEmprunt = panDateEmprunt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PAN_DATE_RETOUR", length = 7)
	public Date getPanDateRetour() {
		return this.panDateRetour;
	}

	public void setPanDateRetour(Date panDateRetour) {
		this.panDateRetour = panDateRetour;
	}

	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bmdPanier")
	public Set<BmdSupportmedia> getBmdSupportmedias() {
		return this.bmdSupportmedias;
	}

	public void setBmdSupportmedias(Set<BmdSupportmedia> bmdSupportmedias) {
		this.bmdSupportmedias = bmdSupportmedias;
	}

	@OneToOne(fetch = FetchType.EAGER, mappedBy = "bmdPanier")
	public BmdReservation getBmdReservations() {
		return this.bmdReservations;
	}

	public void setBmdReservations(BmdReservation bmdReservations) {
		this.bmdReservations = bmdReservations;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bmdPanier")
	public Set<BmdLivre> getBmdLivres() {
		return this.bmdLivres;
	}

	public void setBmdLivres(Set<BmdLivre> bmdLivres) {
		this.bmdLivres = bmdLivres;
	}

}
