package com.projetBMDrive.entities;
// Generated 28 juin 2021 � 11:55:43 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * BmdPanier generated by hbm2java
 */
@Entity
@Table(name = "BMD_PANIER", schema = "BMDRIVE")
public class BmdPanier implements java.io.Serializable {

	private BigDecimal panId;
    private BmdArticle bmdArticle;
    private BmdReservation bmdReservation;
    private Set<BmdVisiteur> bmdVisiteurs = new HashSet<BmdVisiteur>(0);
    private Set<BmdAdherent> bmdAdherents = new HashSet<BmdAdherent>(0);

    public BmdPanier() {
    }

    public BmdPanier(BigDecimal panId) {
        this.panId = panId;
    }

    public BmdPanier(BigDecimal panId, BmdArticle bmdArticle, BmdReservation bmdReservation,
            Set<BmdVisiteur> bmdVisiteurs, Set<BmdAdherent> bmdAdherents) {
        this.panId = panId;
        this.bmdArticle = bmdArticle;
        this.bmdReservation = bmdReservation;
        this.bmdVisiteurs = bmdVisiteurs;
        this.bmdAdherents = bmdAdherents;
    }

    @Id
    @SequenceGenerator(name="BMD_PANIER_SEQ", sequenceName = "BMD_PANIER_SEQ", allocationSize = 1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="BMD_PANIER_SEQ")
    @Column(name = "PAN_ID", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getPanId() {
        return this.panId;
    }

    public void setPanId(BigDecimal panId) {
        this.panId = panId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PAN_ID_ARTICLE")
    public BmdArticle getBmdArticle() {
        return this.bmdArticle;
    }

    public void setBmdArticle(BmdArticle bmdArticle) {
        this.bmdArticle = bmdArticle;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PAN_ID_RESERVATION")
    public BmdReservation getBmdReservation() {
        return this.bmdReservation;
    }

    public void setBmdReservation(BmdReservation bmdReservation) {
        this.bmdReservation = bmdReservation;
    }

    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "bmdPanier")
    public Set<BmdVisiteur> getBmdVisiteurs() {
        return this.bmdVisiteurs;
    }

    public void setBmdVisiteurs(Set<BmdVisiteur> bmdVisiteurs) {
        this.bmdVisiteurs = bmdVisiteurs;
    }

    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "bmdPanier")
    public Set<BmdAdherent> getBmdAdherents() {
        return this.bmdAdherents;
    }

    public void setBmdAdherents(Set<BmdAdherent> bmdAdherents) {
        this.bmdAdherents = bmdAdherents;
    }
}
