package com.projetBMDrive.entities;
// Generated 29 juin 2021 � 14:18:41 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * BmdReservation generated by hbm2java
 */
@Entity
@Table(name = "BMD_RESERVATION", schema = "BMDRIVE")
public class BmdReservation implements java.io.Serializable {

	private BigDecimal resId;
	private BmdPanier bmdPanier;
	private BmdCasier bmdCasiers;

	public BmdReservation() {
	}

	public BmdReservation(BigDecimal resId) {
		this.resId = resId;
	}

	public BmdReservation(BigDecimal resId, BmdPanier bmdPanier, BmdCasier bmdCasiers) {
		this.resId = resId;
		this.bmdPanier = bmdPanier;
		this.bmdCasiers = bmdCasiers;
	}

	@Id
	@SequenceGenerator(name="BMD_RESERVATION_SEQ", sequenceName = "BMD_RESERVATION_SEQ", allocationSize = 1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="BMD_RESERVATION_SEQ")
	@Column(name = "RES_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getResId() {
		return this.resId;
	}

	public void setResId(BigDecimal resId) {
		this.resId = resId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "RES_ID_PANIER")
	public BmdPanier getBmdPanier() {
		return this.bmdPanier;
	}

	public void setBmdPanier(BmdPanier bmdPanier) {
		this.bmdPanier = bmdPanier;
	}

	@OneToOne(fetch = FetchType.EAGER, mappedBy = "bmdReservation")
	public BmdCasier getBmdCasiers() {
		return this.bmdCasiers;
	}

	public void setBmdCasiers(BmdCasier bmdCasiers) {
		this.bmdCasiers = bmdCasiers;
	}

}
