package com.projetBMDrive.entities;
// Generated 28 juin 2021 � 16:47:16 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * BmdReservation generated by hbm2java
 */
@Entity
@Table(name = "BMD_RESERVATION", schema = "BMDRIVE")
public class BmdReservation implements java.io.Serializable {

	private BigDecimal resId;
	private BmdPanier bmdPanier;
	private Set<BmdCasier> bmdCasiers = new HashSet<BmdCasier>(0);
	private Set<BmdAgentbm> bmdAgentbms = new HashSet<BmdAgentbm>(0);

	public BmdReservation() {
	}

	public BmdReservation(BigDecimal resId) {
		this.resId = resId;
	}

	public BmdReservation(BigDecimal resId, BmdPanier bmdPanier, Set<BmdCasier> bmdCasiers,
			Set<BmdAgentbm> bmdAgentbms) {
		this.resId = resId;
		this.bmdPanier = bmdPanier;
		this.bmdCasiers = bmdCasiers;
		this.bmdAgentbms = bmdAgentbms;
	}

	@Id
	@SequenceGenerator(name="BMD_RESERVATION_SEQ", sequenceName = "BMD_RESERVATION_SEQ", allocationSize = 1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="BMD_RESERVATION_SEQ")
	@Column(name = "RES_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getResId() {
		return this.resId;
	}

	public void setResId(BigDecimal resId) {
		this.resId = resId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "RES_ID_PANIER")
	public BmdPanier getBmdPanier() {
		return this.bmdPanier;
	}

	public void setBmdPanier(BmdPanier bmdPanier) {
		this.bmdPanier = bmdPanier;
	}
	
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bmdReservation")
	public Set<BmdCasier> getBmdCasiers() {
		return this.bmdCasiers;
	}

	public void setBmdCasiers(Set<BmdCasier> bmdCasiers) {
		this.bmdCasiers = bmdCasiers;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bmdReservation")
	public Set<BmdAgentbm> getBmdAgentbms() {
		return this.bmdAgentbms;
	}

	public void setBmdAgentbms(Set<BmdAgentbm> bmdAgentbms) {
		this.bmdAgentbms = bmdAgentbms;
	}

}
