package com.projetBMDrive.entities;
// Generated 29 juin 2021 � 14:18:41 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * BmdSupportmedia generated by hbm2java
 */
@Entity
@Table(name = "BMD_SUPPORTMEDIA", schema = "BMDRIVE")
public class BmdSupportmedia implements java.io.Serializable {

	private BigDecimal supId;
	private BmdArticle bmdArticle;
	private BmdCategorie bmdCategorie;
	private BmdPanier bmdPanier;
	private String supType;

	public BmdSupportmedia() {
	}

	public BmdSupportmedia(BigDecimal supId, BmdArticle bmdArticle, BmdCategorie bmdCategorie, String supType) {
		this.supId = supId;
		this.bmdArticle = bmdArticle;
		this.bmdCategorie = bmdCategorie;
		this.supType = supType;
	}

	public BmdSupportmedia(BigDecimal supId, BmdArticle bmdArticle, BmdCategorie bmdCategorie, BmdPanier bmdPanier,
			String supType) {
		this.supId = supId;
		this.bmdArticle = bmdArticle;
		this.bmdCategorie = bmdCategorie;
		this.bmdPanier = bmdPanier;
		this.supType = supType;
	}

	@Id
	@SequenceGenerator(name="BMD_SUPPORTMEDIA_SEQ", sequenceName = "BMD_SUPPORTMEDIA_SEQ", allocationSize = 1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="BMD_SUPPORTMEDIA_SEQ")
	@Column(name = "SUP_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getSupId() {
		return this.supId;
	}

	public void setSupId(BigDecimal supId) {
		this.supId = supId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SUP_ARTICLE_ID", nullable = false)
	public BmdArticle getBmdArticle() {
		return this.bmdArticle;
	}

	public void setBmdArticle(BmdArticle bmdArticle) {
		this.bmdArticle = bmdArticle;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SUP_CAT_ID", nullable = false)
	public BmdCategorie getBmdCategorie() {
		return this.bmdCategorie;
	}

	public void setBmdCategorie(BmdCategorie bmdCategorie) {
		this.bmdCategorie = bmdCategorie;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SUP_PAN_ID")
	public BmdPanier getBmdPanier() {
		return this.bmdPanier;
	}

	public void setBmdPanier(BmdPanier bmdPanier) {
		this.bmdPanier = bmdPanier;
	}

	@Column(name = "SUP_TYPE", nullable = false, length = 320)
	public String getSupType() {
		return this.supType;
	}

	public void setSupType(String supType) {
		this.supType = supType;
	}

}
