package com.projetBMDrive.entities;
// Generated 28 juin 2021 � 16:47:16 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * BmdSupportmedia generated by hbm2java
 */
@Entity
@Table(name = "BMD_SUPPORTMEDIA", schema = "BMDRIVE")
public class BmdSupportmedia implements java.io.Serializable {

	private BigDecimal supId;
	private BmdArticle bmdArticle;
	private String supType;
	private Set<BmdCategorie> bmdCategories = new HashSet<BmdCategorie>(0);
	private Set<BmdPanier> bmdPaniers = new HashSet<BmdPanier>(0);

	public BmdSupportmedia() {
	}

	public BmdSupportmedia(BigDecimal supId, BmdArticle bmdArticle, String supType) {
		this.supId = supId;
		this.bmdArticle = bmdArticle;
		this.supType = supType;
	}

	public BmdSupportmedia(BigDecimal supId, BmdArticle bmdArticle, String supType, Set<BmdCategorie> bmdCategories,
			Set<BmdPanier> bmdPaniers) {
		this.supId = supId;
		this.bmdArticle = bmdArticle;
		this.supType = supType;
		this.bmdCategories = bmdCategories;
		this.bmdPaniers = bmdPaniers;
	}

	@Id
	@SequenceGenerator(name="BMD_SUPPORTMEDIA_SEQ", sequenceName = "BMD_SUPPORTMEDIA_SEQ", allocationSize = 1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="BMD_SUPPORTMEDIA_SEQ")
	@Column(name = "SUP_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getSupId() {
		return this.supId;
	}

	public void setSupId(BigDecimal supId) {
		this.supId = supId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SUP_ARTICLE_ID", nullable = false)
	public BmdArticle getBmdArticle() {
		return this.bmdArticle;
	}

	public void setBmdArticle(BmdArticle bmdArticle) {
		this.bmdArticle = bmdArticle;
	}

	@Column(name = "SUP_TYPE", nullable = false, length = 80)
	public String getSupType() {
		return this.supType;
	}

	public void setSupType(String supType) {
		this.supType = supType;
	}
	
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bmdSupportmedia")
	public Set<BmdCategorie> getBmdCategories() {
		return this.bmdCategories;
	}

	public void setBmdCategories(Set<BmdCategorie> bmdCategories) {
		this.bmdCategories = bmdCategories;
	}
	
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bmdSupportmedia")
	public Set<BmdPanier> getBmdPaniers() {
		return this.bmdPaniers;
	}

	public void setBmdPaniers(Set<BmdPanier> bmdPaniers) {
		this.bmdPaniers = bmdPaniers;
	}

}
