package com.projetBMDrive.entities;
// Generated 8 juin 2021 � 11:44:16 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TAdherent generated by hbm2java
 */
@Entity
@Table(name = "T_ADHERENT", schema = "BMDRIVE")
public class TAdherent implements java.io.Serializable {

	private BigDecimal adhIdLecteur;
	private TIdentite TIdentite;
	private TPanier TPanier;
	private String adhNomUtilisateur;
	private String adhMotDePasse;

	public TAdherent() {
	}

	public TAdherent(BigDecimal adhIdLecteur, TIdentite TIdentite, TPanier TPanier, String adhNomUtilisateur,
			String adhMotDePasse) {
		this.adhIdLecteur = adhIdLecteur;
		this.TIdentite = TIdentite;
		this.TPanier = TPanier;
		this.adhNomUtilisateur = adhNomUtilisateur;
		this.adhMotDePasse = adhMotDePasse;
	}

	@Id

	@Column(name = "ADH_ID_LECTEUR", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getAdhIdLecteur() {
		return this.adhIdLecteur;
	}

	public void setAdhIdLecteur(BigDecimal adhIdLecteur) {
		this.adhIdLecteur = adhIdLecteur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ADH_ID_IDENTITE", nullable = false)
	public TIdentite getTIdentite() {
		return this.TIdentite;
	}

	public void setTIdentite(TIdentite TIdentite) {
		this.TIdentite = TIdentite;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ADH_ID_PANIER", nullable = false)
	public TPanier getTPanier() {
		return this.TPanier;
	}

	public void setTPanier(TPanier TPanier) {
		this.TPanier = TPanier;
	}

	@Column(name = "ADH_NOM_UTILISATEUR", nullable = false, length = 20)
	public String getAdhNomUtilisateur() {
		return this.adhNomUtilisateur;
	}

	public void setAdhNomUtilisateur(String adhNomUtilisateur) {
		this.adhNomUtilisateur = adhNomUtilisateur;
	}

	@Column(name = "ADH_MOT_DE_PASSE", nullable = false, length = 20)
	public String getAdhMotDePasse() {
		return this.adhMotDePasse;
	}

	public void setAdhMotDePasse(String adhMotDePasse) {
		this.adhMotDePasse = adhMotDePasse;
	}

}
