package com.projetBMDrive.entities;
// Generated 14 juin 2021 � 17:47:08 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TAdherent generated by hbm2java
 */
@Entity
@Table(name = "T_ADHERENT", schema = "BMDRIVE")
public class TAdherent implements java.io.Serializable {

	private BigDecimal adhId;
	private TIdentite TIdentite;
	private TPanier TPanier;
	private String adhNomUtilisateur;
	private String adhMotDePasse;

	public TAdherent() {
	}

	public TAdherent(BigDecimal adhId) {
		this.adhId = adhId;
	}

	public TAdherent(BigDecimal adhId, TIdentite TIdentite, TPanier TPanier, String adhNomUtilisateur,
			String adhMotDePasse) {
		this.adhId = adhId;
		this.TIdentite = TIdentite;
		this.TPanier = TPanier;
		this.adhNomUtilisateur = adhNomUtilisateur;
		this.adhMotDePasse = adhMotDePasse;
	}

	@Id
	@SequenceGenerator(name="T_ADHERENT_SEQ", sequenceName = "T_ADHERENT_SEQ", allocationSize = 1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="T_ADHERENT_SEQ")
	@Column(name = "ADH_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getAdhId() {
		return this.adhId;
	}

	public void setAdhId(BigDecimal adhId) {
		this.adhId = adhId;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ADH_ID_IDENTITE")
	public TIdentite getTIdentite() {
		return this.TIdentite;
	}

	public void setTIdentite(TIdentite TIdentite) {
		this.TIdentite = TIdentite;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ADH_ID_PANIER")
	public TPanier getTPanier() {
		return this.TPanier;
	}

	public void setTPanier(TPanier TPanier) {
		this.TPanier = TPanier;
	}

	@Column(name = "ADH_NOM_UTILISATEUR", length = 20)
	public String getAdhNomUtilisateur() {
		return this.adhNomUtilisateur;
	}

	public void setAdhNomUtilisateur(String adhNomUtilisateur) {
		this.adhNomUtilisateur = adhNomUtilisateur;
	}

	@Column(name = "ADH_MOT_DE_PASSE", length = 20)
	public String getAdhMotDePasse() {
		return this.adhMotDePasse;
	}

	public void setAdhMotDePasse(String adhMotDePasse) {
		this.adhMotDePasse = adhMotDePasse;
	}

}
