package com.projetBMDrive.entities;
// Generated 8 juin 2021 � 13:57:09 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TAdresse generated by hbm2java
 */
@Entity
@Table(name = "T_ADRESSE", schema = "BMDRIVE")
public class TAdresse implements java.io.Serializable {

	private BigDecimal adrId;
	private BigDecimal adrNumRue;
	private String adrNomRue;
	private String adrCplAdr;
	private BigDecimal adrCp;
	private String adrVille;
	private Set<TIdentite> TIdentites = new HashSet<TIdentite>(0);

	public TAdresse() {
	}

	public TAdresse(BigDecimal adrId, BigDecimal adrNumRue, String adrNomRue, String adrCplAdr, BigDecimal adrCp,
			String adrVille) {
		this.adrId = adrId;
		this.adrNumRue = adrNumRue;
		this.adrNomRue = adrNomRue;
		this.adrCplAdr = adrCplAdr;
		this.adrCp = adrCp;
		this.adrVille = adrVille;
	}

	public TAdresse(BigDecimal adrId, BigDecimal adrNumRue, String adrNomRue, String adrCplAdr, BigDecimal adrCp,
			String adrVille, Set<TIdentite> TIdentites) {
		this.adrId = adrId;
		this.adrNumRue = adrNumRue;
		this.adrNomRue = adrNomRue;
		this.adrCplAdr = adrCplAdr;
		this.adrCp = adrCp;
		this.adrVille = adrVille;
		this.TIdentites = TIdentites;
	}

	@Id

	@Column(name = "ADR_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getAdrId() {
		return this.adrId;
	}

	public void setAdrId(BigDecimal adrId) {
		this.adrId = adrId;
	}

	@Column(name = "ADR_NUM_RUE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getAdrNumRue() {
		return this.adrNumRue;
	}

	public void setAdrNumRue(BigDecimal adrNumRue) {
		this.adrNumRue = adrNumRue;
	}

	@Column(name = "ADR_NOM_RUE", nullable = false, length = 30)
	public String getAdrNomRue() {
		return this.adrNomRue;
	}

	public void setAdrNomRue(String adrNomRue) {
		this.adrNomRue = adrNomRue;
	}

	@Column(name = "ADR_CPL_ADR", nullable = false, length = 20)
	public String getAdrCplAdr() {
		return this.adrCplAdr;
	}

	public void setAdrCplAdr(String adrCplAdr) {
		this.adrCplAdr = adrCplAdr;
	}

	@Column(name = "ADR_CP", nullable = false, precision = 22, scale = 0)
	public BigDecimal getAdrCp() {
		return this.adrCp;
	}

	public void setAdrCp(BigDecimal adrCp) {
		this.adrCp = adrCp;
	}

	@Column(name = "ADR_VILLE", nullable = false, length = 30)
	public String getAdrVille() {
		return this.adrVille;
	}

	public void setAdrVille(String adrVille) {
		this.adrVille = adrVille;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TAdresse")
	public Set<TIdentite> getTIdentites() {
		return this.TIdentites;
	}

	public void setTIdentites(Set<TIdentite> TIdentites) {
		this.TIdentites = TIdentites;
	}

}
