package com.projetBMDrive.entities;
// Generated 14 juin 2021 � 17:47:08 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TAgentbm generated by hbm2java
 */
@Entity
@Table(name = "T_AGENTBM", schema = "BMDRIVE")
public class TAgentbm implements java.io.Serializable {

	private BigDecimal abmId;
	private TIdentite TIdentite;
	private TReservation TReservation;
	private String abmNomUtilisateur;
	private String abmMotDePasse;

	public TAgentbm() {
	}

	public TAgentbm(BigDecimal abmId, String abmNomUtilisateur, String abmMotDePasse) {
		this.abmId = abmId;
		this.abmNomUtilisateur = abmNomUtilisateur;
		this.abmMotDePasse = abmMotDePasse;
	}

	public TAgentbm(BigDecimal abmId, TIdentite TIdentite, TReservation TReservation, String abmNomUtilisateur,
			String abmMotDePasse) {
		this.abmId = abmId;
		this.TIdentite = TIdentite;
		this.TReservation = TReservation;
		this.abmNomUtilisateur = abmNomUtilisateur;
		this.abmMotDePasse = abmMotDePasse;
	}

	@Id
	@SequenceGenerator(name="T_AGENTBM_SEQ", sequenceName = "T_AGENTBM_SEQ", allocationSize = 1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="T_AGENTBM_SEQ")
	@Column(name = "ABM_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getAbmId() {
		return this.abmId;
	}

	public void setAbmId(BigDecimal abmId) {
		this.abmId = abmId;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ABM_ID_IDENTITE")
	public TIdentite getTIdentite() {
		return this.TIdentite;
	}

	public void setTIdentite(TIdentite TIdentite) {
		this.TIdentite = TIdentite;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ABM_ID_RESERVATION")
	public TReservation getTReservation() {
		return this.TReservation;
	}

	public void setTReservation(TReservation TReservation) {
		this.TReservation = TReservation;
	}

	@Column(name = "ABM_NOM_UTILISATEUR", nullable = false, length = 20)
	public String getAbmNomUtilisateur() {
		return this.abmNomUtilisateur;
	}

	public void setAbmNomUtilisateur(String abmNomUtilisateur) {
		this.abmNomUtilisateur = abmNomUtilisateur;
	}

	@Column(name = "ABM_MOT_DE_PASSE", nullable = false, length = 20)
	public String getAbmMotDePasse() {
		return this.abmMotDePasse;
	}

	public void setAbmMotDePasse(String abmMotDePasse) {
		this.abmMotDePasse = abmMotDePasse;
	}

}
