package com.projetBMDrive.entities;
// Generated 14 juin 2021 � 17:47:08 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TArticle generated by hbm2java
 */
@Entity
@Table(name = "T_ARTICLE", schema = "BMDRIVE")
public class TArticle implements java.io.Serializable {

	private BigDecimal artId;
	private String artCote;
	private String artTitre;
	private String artAuteur;
	private Date artDateEmprunt;
	private Date artDateRetour;
	private Set<TLivre> TLivres = new HashSet<TLivre>(0);
	private Set<TPanier> TPaniers = new HashSet<TPanier>(0);
	private Set<TCategorie> TCategories = new HashSet<TCategorie>(0);
	private Set<TSupportmedia> TSupportmedias = new HashSet<TSupportmedia>(0);

	public TArticle() {
	}

	public TArticle(BigDecimal artId, String artTitre, String artAuteur) {
		this.artId = artId;
		this.artTitre = artTitre;
		this.artAuteur = artAuteur;
	}

	public TArticle(BigDecimal artId, String artCote, String artTitre, String artAuteur, Date artDateEmprunt,
			Date artDateRetour, Set<TLivre> TLivres, Set<TPanier> TPaniers, Set<TCategorie> TCategories,
			Set<TSupportmedia> TSupportmedias) {
		this.artId = artId;
		this.artCote = artCote;
		this.artTitre = artTitre;
		this.artAuteur = artAuteur;
		this.artDateEmprunt = artDateEmprunt;
		this.artDateRetour = artDateRetour;
		this.TLivres = TLivres;
		this.TPaniers = TPaniers;
		this.TCategories = TCategories;
		this.TSupportmedias = TSupportmedias;
	}

	@Id
	@SequenceGenerator(name="T_ARTICLE_SEQ", sequenceName = "T_ARTICLE_SEQ", allocationSize = 1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="T_ARTICLE_SEQ")
	@Column(name = "ART_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getArtId() {
		return this.artId;
	}

	public void setArtId(BigDecimal artId) {
		this.artId = artId;
	}

	@Column(name = "ART_COTE", length = 20)
	public String getArtCote() {
		return this.artCote;
	}

	public void setArtCote(String artCote) {
		this.artCote = artCote;
	}

	@Column(name = "ART_TITRE", nullable = false, length = 40)
	public String getArtTitre() {
		return this.artTitre;
	}

	public void setArtTitre(String artTitre) {
		this.artTitre = artTitre;
	}

	@Column(name = "ART_AUTEUR", nullable = false, length = 40)
	public String getArtAuteur() {
		return this.artAuteur;
	}

	public void setArtAuteur(String artAuteur) {
		this.artAuteur = artAuteur;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ART_DATE_EMPRUNT", length = 7)
	public Date getArtDateEmprunt() {
		return this.artDateEmprunt;
	}

	public void setArtDateEmprunt(Date artDateEmprunt) {
		this.artDateEmprunt = artDateEmprunt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ART_DATE_RETOUR", length = 7)
	public Date getArtDateRetour() {
		return this.artDateRetour;
	}

	public void setArtDateRetour(Date artDateRetour) {
		this.artDateRetour = artDateRetour;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TArticle")
	public Set<TLivre> getTLivres() {
		return this.TLivres;
	}

	public void setTLivres(Set<TLivre> TLivres) {
		this.TLivres = TLivres;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TArticle")
	public Set<TPanier> getTPaniers() {
		return this.TPaniers;
	}

	public void setTPaniers(Set<TPanier> TPaniers) {
		this.TPaniers = TPaniers;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TArticle")
	public Set<TCategorie> getTCategories() {
		return this.TCategories;
	}

	public void setTCategories(Set<TCategorie> TCategories) {
		this.TCategories = TCategories;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TArticle")
	public Set<TSupportmedia> getTSupportmedias() {
		return this.TSupportmedias;
	}

	public void setTSupportmedias(Set<TSupportmedia> TSupportmedias) {
		this.TSupportmedias = TSupportmedias;
	}

}
