package com.projetBMDrive.entities;
// Generated 8 juin 2021 � 13:57:09 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TArticle generated by hbm2java
 */
@Entity
@Table(name = "T_ARTICLE", schema = "BMDRIVE")
public class TArticle implements java.io.Serializable {

	private BigDecimal artIdObjet;
	private String artCote;
	private String artTitre;
	private String artAuteur;
	private Date artDateEmprunt;
	private Date artDateRetour;
	private Set<TLivre> TLivres = new HashSet<TLivre>(0);
	private Set<TSupportmedia> TSupportmedias = new HashSet<TSupportmedia>(0);
	private Set<TPanier> TPaniers = new HashSet<TPanier>(0);
	private Set<TCategorie> TCategories = new HashSet<TCategorie>(0);

	public TArticle() {
	}

	public TArticle(BigDecimal artIdObjet, String artCote, String artTitre, String artAuteur, Date artDateEmprunt,
			Date artDateRetour) {
		this.artIdObjet = artIdObjet;
		this.artCote = artCote;
		this.artTitre = artTitre;
		this.artAuteur = artAuteur;
		this.artDateEmprunt = artDateEmprunt;
		this.artDateRetour = artDateRetour;
	}

	public TArticle(BigDecimal artIdObjet, String artCote, String artTitre, String artAuteur, Date artDateEmprunt,
			Date artDateRetour, Set<TLivre> TLivres, Set<TSupportmedia> TSupportmedias, Set<TPanier> TPaniers,
			Set<TCategorie> TCategories) {
		this.artIdObjet = artIdObjet;
		this.artCote = artCote;
		this.artTitre = artTitre;
		this.artAuteur = artAuteur;
		this.artDateEmprunt = artDateEmprunt;
		this.artDateRetour = artDateRetour;
		this.TLivres = TLivres;
		this.TSupportmedias = TSupportmedias;
		this.TPaniers = TPaniers;
		this.TCategories = TCategories;
	}

	@Id

	@Column(name = "ART_ID_OBJET", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getArtIdObjet() {
		return this.artIdObjet;
	}

	public void setArtIdObjet(BigDecimal artIdObjet) {
		this.artIdObjet = artIdObjet;
	}

	@Column(name = "ART_COTE", nullable = false, length = 20)
	public String getArtCote() {
		return this.artCote;
	}

	public void setArtCote(String artCote) {
		this.artCote = artCote;
	}

	@Column(name = "ART_TITRE", nullable = false, length = 40)
	public String getArtTitre() {
		return this.artTitre;
	}

	public void setArtTitre(String artTitre) {
		this.artTitre = artTitre;
	}

	@Column(name = "ART_AUTEUR", nullable = false, length = 40)
	public String getArtAuteur() {
		return this.artAuteur;
	}

	public void setArtAuteur(String artAuteur) {
		this.artAuteur = artAuteur;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ART_DATE_EMPRUNT", nullable = false, length = 7)
	public Date getArtDateEmprunt() {
		return this.artDateEmprunt;
	}

	public void setArtDateEmprunt(Date artDateEmprunt) {
		this.artDateEmprunt = artDateEmprunt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ART_DATE_RETOUR", nullable = false, length = 7)
	public Date getArtDateRetour() {
		return this.artDateRetour;
	}

	public void setArtDateRetour(Date artDateRetour) {
		this.artDateRetour = artDateRetour;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TArticle")
	public Set<TLivre> getTLivres() {
		return this.TLivres;
	}

	public void setTLivres(Set<TLivre> TLivres) {
		this.TLivres = TLivres;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TArticle")
	public Set<TSupportmedia> getTSupportmedias() {
		return this.TSupportmedias;
	}

	public void setTSupportmedias(Set<TSupportmedia> TSupportmedias) {
		this.TSupportmedias = TSupportmedias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TArticle")
	public Set<TPanier> getTPaniers() {
		return this.TPaniers;
	}

	public void setTPaniers(Set<TPanier> TPaniers) {
		this.TPaniers = TPaniers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TArticle")
	public Set<TCategorie> getTCategories() {
		return this.TCategories;
	}

	public void setTCategories(Set<TCategorie> TCategories) {
		this.TCategories = TCategories;
	}

}
