package com.projetBMDrive.entities;
// Generated 8 juin 2021 � 13:57:09 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TCasier generated by hbm2java
 */
@Entity
@Table(name = "T_CASIER", schema = "BMDRIVE")
public class TCasier implements java.io.Serializable {

	private BigDecimal casId;
	private Set<TReservation> TReservations = new HashSet<TReservation>(0);

	public TCasier() {
	}

	public TCasier(BigDecimal casId) {
		this.casId = casId;
	}

	public TCasier(BigDecimal casId, Set<TReservation> TReservations) {
		this.casId = casId;
		this.TReservations = TReservations;
	}

	@Id

	@Column(name = "CAS_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getCasId() {
		return this.casId;
	}

	public void setCasId(BigDecimal casId) {
		this.casId = casId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCasier")
	public Set<TReservation> getTReservations() {
		return this.TReservations;
	}

	public void setTReservations(Set<TReservation> TReservations) {
		this.TReservations = TReservations;
	}

}
