package com.projetBMDrive.entities;
// Generated 14 juin 2021 � 17:47:08 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TCasier generated by hbm2java
 */
@Entity
@Table(name = "T_CASIER", schema = "BMDRIVE")
public class TCasier implements java.io.Serializable {

	private BigDecimal casId;
	private String casNumero;
	private Set<TReservation> TReservations = new HashSet<TReservation>(0);

	public TCasier() {
	}

	public TCasier(BigDecimal casId, String casNumero) {
		this.casId = casId;
		this.casNumero = casNumero;
	}

	public TCasier(BigDecimal casId, String casNumero, Set<TReservation> TReservations) {
		this.casId = casId;
		this.casNumero = casNumero;
		this.TReservations = TReservations;
	}

	@Id
	@SequenceGenerator(name="T_CASIER_SEQ", sequenceName = "T_CASIER_SEQ", allocationSize = 1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="T_CASIER_SEQ")
	@Column(name = "CAS_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getCasId() {
		return this.casId;
	}

	public void setCasId(BigDecimal casId) {
		this.casId = casId;
	}

	@Column(name = "CAS_NUMERO", nullable = false, length = 20)
	public String getCasNumero() {
		return this.casNumero;
	}

	public void setCasNumero(String casNumero) {
		this.casNumero = casNumero;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCasier")
	public Set<TReservation> getTReservations() {
		return this.TReservations;
	}

	public void setTReservations(Set<TReservation> TReservations) {
		this.TReservations = TReservations;
	}

}
