package com.projetBMDrive.entities;
// Generated 14 juin 2021 � 17:47:08 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TCategorie generated by hbm2java
 */
@Entity
@Table(name = "T_CATEGORIE", schema = "BMDRIVE")
public class TCategorie implements java.io.Serializable {

	private BigDecimal catId;
	private TArticle TArticle;
	private String catLibelle;

	public TCategorie() {
	}

	public TCategorie(BigDecimal catId, String catLibelle) {
		this.catId = catId;
		this.catLibelle = catLibelle;
	}

	public TCategorie(BigDecimal catId, TArticle TArticle, String catLibelle) {
		this.catId = catId;
		this.TArticle = TArticle;
		this.catLibelle = catLibelle;
	}

	@Id
	@SequenceGenerator(name="T_CATEGORIE_SEQ", sequenceName = "T_CATEGORIE_SEQ", allocationSize = 1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="T_CATEGORIE_SEQ")
	@Column(name = "CAT_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getCatId() {
		return this.catId;
	}

	public void setCatId(BigDecimal catId) {
		this.catId = catId;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CAT_ARTICLE_ID")
	public TArticle getTArticle() {
		return this.TArticle;
	}

	public void setTArticle(TArticle TArticle) {
		this.TArticle = TArticle;
	}

	@Column(name = "CAT_LIBELLE", nullable = false, length = 20)
	public String getCatLibelle() {
		return this.catLibelle;
	}

	public void setCatLibelle(String catLibelle) {
		this.catLibelle = catLibelle;
	}

}
