package com.projetBMDrive.entities;
// Generated 8 juin 2021 � 13:57:09 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TIdentite generated by hbm2java
 */
@Entity
@Table(name = "T_IDENTITE", schema = "BMDRIVE")
public class TIdentite implements java.io.Serializable {

	private BigDecimal ideIdentite;
	private TAdresse TAdresse;
	private String ideNom;
	private String idePrenom;
	private BigDecimal ideAge;
	private char ideSexe;
	private String ideTelephone;
	private String ideMail;
	private Set<TAgentbm> TAgentbms = new HashSet<TAgentbm>(0);
	private Set<TVisiteur> TVisiteurs = new HashSet<TVisiteur>(0);
	private Set<TAdherent> TAdherents = new HashSet<TAdherent>(0);

	public TIdentite() {
	}

	public TIdentite(BigDecimal ideIdentite, TAdresse TAdresse, String ideNom, String idePrenom, BigDecimal ideAge,
			char ideSexe, String ideTelephone, String ideMail) {
		this.ideIdentite = ideIdentite;
		this.TAdresse = TAdresse;
		this.ideNom = ideNom;
		this.idePrenom = idePrenom;
		this.ideAge = ideAge;
		this.ideSexe = ideSexe;
		this.ideTelephone = ideTelephone;
		this.ideMail = ideMail;
	}

	public TIdentite(BigDecimal ideIdentite, TAdresse TAdresse, String ideNom, String idePrenom, BigDecimal ideAge,
			char ideSexe, String ideTelephone, String ideMail, Set<TAgentbm> TAgentbms, Set<TVisiteur> TVisiteurs,
			Set<TAdherent> TAdherents) {
		this.ideIdentite = ideIdentite;
		this.TAdresse = TAdresse;
		this.ideNom = ideNom;
		this.idePrenom = idePrenom;
		this.ideAge = ideAge;
		this.ideSexe = ideSexe;
		this.ideTelephone = ideTelephone;
		this.ideMail = ideMail;
		this.TAgentbms = TAgentbms;
		this.TVisiteurs = TVisiteurs;
		this.TAdherents = TAdherents;
	}

	@Id

	@Column(name = "IDE_IDENTITE", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdeIdentite() {
		return this.ideIdentite;
	}

	public void setIdeIdentite(BigDecimal ideIdentite) {
		this.ideIdentite = ideIdentite;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDE_ADRESSE", nullable = false)
	public TAdresse getTAdresse() {
		return this.TAdresse;
	}

	public void setTAdresse(TAdresse TAdresse) {
		this.TAdresse = TAdresse;
	}

	@Column(name = "IDE_NOM", nullable = false, length = 40)
	public String getIdeNom() {
		return this.ideNom;
	}

	public void setIdeNom(String ideNom) {
		this.ideNom = ideNom;
	}

	@Column(name = "IDE_PRENOM", nullable = false, length = 30)
	public String getIdePrenom() {
		return this.idePrenom;
	}

	public void setIdePrenom(String idePrenom) {
		this.idePrenom = idePrenom;
	}

	@Column(name = "IDE_AGE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdeAge() {
		return this.ideAge;
	}

	public void setIdeAge(BigDecimal ideAge) {
		this.ideAge = ideAge;
	}

	@Column(name = "IDE_SEXE", nullable = false, length = 1)
	public char getIdeSexe() {
		return this.ideSexe;
	}

	public void setIdeSexe(char ideSexe) {
		this.ideSexe = ideSexe;
	}

	@Column(name = "IDE_TELEPHONE", nullable = false, length = 20)
	public String getIdeTelephone() {
		return this.ideTelephone;
	}

	public void setIdeTelephone(String ideTelephone) {
		this.ideTelephone = ideTelephone;
	}

	@Column(name = "IDE_MAIL", nullable = false, length = 40)
	public String getIdeMail() {
		return this.ideMail;
	}

	public void setIdeMail(String ideMail) {
		this.ideMail = ideMail;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TIdentite")
	public Set<TAgentbm> getTAgentbms() {
		return this.TAgentbms;
	}

	public void setTAgentbms(Set<TAgentbm> TAgentbms) {
		this.TAgentbms = TAgentbms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TIdentite")
	public Set<TVisiteur> getTVisiteurs() {
		return this.TVisiteurs;
	}

	public void setTVisiteurs(Set<TVisiteur> TVisiteurs) {
		this.TVisiteurs = TVisiteurs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TIdentite")
	public Set<TAdherent> getTAdherents() {
		return this.TAdherents;
	}

	public void setTAdherents(Set<TAdherent> TAdherents) {
		this.TAdherents = TAdherents;
	}

}
