package com.projetBMDrive.entities;
// Generated 8 juin 2021 � 13:57:09 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TLivre generated by hbm2java
 */
@Entity
@Table(name = "T_LIVRE", schema = "BMDRIVE")
public class TLivre implements java.io.Serializable {

	private BigDecimal livId;
	private TArticle TArticle;
	private BigDecimal livNbPages;

	public TLivre() {
	}

	public TLivre(BigDecimal livId, TArticle TArticle, BigDecimal livNbPages) {
		this.livId = livId;
		this.TArticle = TArticle;
		this.livNbPages = livNbPages;
	}

	@Id

	@Column(name = "LIV_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getLivId() {
		return this.livId;
	}

	public void setLivId(BigDecimal livId) {
		this.livId = livId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LIV_OBJET_ID", nullable = false)
	public TArticle getTArticle() {
		return this.TArticle;
	}

	public void setTArticle(TArticle TArticle) {
		this.TArticle = TArticle;
	}

	@Column(name = "LIV_NB_PAGES", nullable = false, precision = 22, scale = 0)
	public BigDecimal getLivNbPages() {
		return this.livNbPages;
	}

	public void setLivNbPages(BigDecimal livNbPages) {
		this.livNbPages = livNbPages;
	}

}
