package com.projetBMDrive.entities;
// Generated 8 juin 2021 � 11:44:16 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TLivreId generated by hbm2java
 */
@Embeddable
public class TLivreId implements java.io.Serializable {

	private BigDecimal livNbPages;
	private BigDecimal livObjetId;

	public TLivreId() {
	}

	public TLivreId(BigDecimal livNbPages, BigDecimal livObjetId) {
		this.livNbPages = livNbPages;
		this.livObjetId = livObjetId;
	}

	@Column(name = "LIV_NB_PAGES", nullable = false, precision = 22, scale = 0)
	public BigDecimal getLivNbPages() {
		return this.livNbPages;
	}

	public void setLivNbPages(BigDecimal livNbPages) {
		this.livNbPages = livNbPages;
	}

	@Column(name = "LIV_OBJET_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getLivObjetId() {
		return this.livObjetId;
	}

	public void setLivObjetId(BigDecimal livObjetId) {
		this.livObjetId = livObjetId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TLivreId))
			return false;
		TLivreId castOther = (TLivreId) other;

		return ((this.getLivNbPages() == castOther.getLivNbPages()) || (this.getLivNbPages() != null
				&& castOther.getLivNbPages() != null && this.getLivNbPages().equals(castOther.getLivNbPages())))
				&& ((this.getLivObjetId() == castOther.getLivObjetId())
						|| (this.getLivObjetId() != null && castOther.getLivObjetId() != null
								&& this.getLivObjetId().equals(castOther.getLivObjetId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getLivNbPages() == null ? 0 : this.getLivNbPages().hashCode());
		result = 37 * result + (getLivObjetId() == null ? 0 : this.getLivObjetId().hashCode());
		return result;
	}

}
