package com.projetBMDrive.entities;
// Generated 8 juin 2021 � 11:44:16 by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TLivre generated by hbm2java
 */
@Entity
@Table(name = "T_LIVRE", schema = "BMDRIVE")
public class TLivre implements java.io.Serializable {

	private TLivreId id;
	private TArticle TArticle;

	public TLivre() {
	}

	public TLivre(TLivreId id, TArticle TArticle) {
		this.id = id;
		this.TArticle = TArticle;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "livNbPages", column = @Column(name = "LIV_NB_PAGES", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "livObjetId", column = @Column(name = "LIV_OBJET_ID", nullable = false, precision = 22, scale = 0)) })
	public TLivreId getId() {
		return this.id;
	}

	public void setId(TLivreId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LIV_OBJET_ID", nullable = false, insertable = false, updatable = false)
	public TArticle getTArticle() {
		return this.TArticle;
	}

	public void setTArticle(TArticle TArticle) {
		this.TArticle = TArticle;
	}

}
