package com.projetBMDrive.entities;
// Generated 14 juin 2021 � 17:47:08 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TPanier generated by hbm2java
 */
@Entity
@Table(name = "T_PANIER", schema = "BMDRIVE")
public class TPanier implements java.io.Serializable {

	private BigDecimal panId;
	private TArticle TArticle;
	private TReservation TReservation;
	private Set<TVisiteur> TVisiteurs = new HashSet<TVisiteur>(0);
	private Set<TAdherent> TAdherents = new HashSet<TAdherent>(0);

	public TPanier() {
	}

	public TPanier(BigDecimal panId) {
		this.panId = panId;
	}

	public TPanier(BigDecimal panId, TArticle TArticle, TReservation TReservation, Set<TVisiteur> TVisiteurs,
			Set<TAdherent> TAdherents) {
		this.panId = panId;
		this.TArticle = TArticle;
		this.TReservation = TReservation;
		this.TVisiteurs = TVisiteurs;
		this.TAdherents = TAdherents;
	}

	@Id
	@SequenceGenerator(name="T_PANIER_SEQ", sequenceName = "T_PANIER_SEQ", allocationSize = 1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="T_PANIER_SEQ")
	@Column(name = "PAN_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getPanId() {
		return this.panId;
	}

	public void setPanId(BigDecimal panId) {
		this.panId = panId;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PAN_ID_ARTICLE")
	public TArticle getTArticle() {
		return this.TArticle;
	}

	public void setTArticle(TArticle TArticle) {
		this.TArticle = TArticle;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PAN_ID_RESERVATION")
	public TReservation getTReservation() {
		return this.TReservation;
	}

	public void setTReservation(TReservation TReservation) {
		this.TReservation = TReservation;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TPanier")
	public Set<TVisiteur> getTVisiteurs() {
		return this.TVisiteurs;
	}

	public void setTVisiteurs(Set<TVisiteur> TVisiteurs) {
		this.TVisiteurs = TVisiteurs;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TPanier")
	public Set<TAdherent> getTAdherents() {
		return this.TAdherents;
	}

	public void setTAdherents(Set<TAdherent> TAdherents) {
		this.TAdherents = TAdherents;
	}

}
