package com.projetBMDrive.entities;
// Generated 8 juin 2021 � 11:44:16 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TSupportmediaId generated by hbm2java
 */
@Embeddable
public class TSupportmediaId implements java.io.Serializable {

	private String supType;
	private BigDecimal supDuree;
	private BigDecimal supObjetId;

	public TSupportmediaId() {
	}

	public TSupportmediaId(String supType, BigDecimal supDuree, BigDecimal supObjetId) {
		this.supType = supType;
		this.supDuree = supDuree;
		this.supObjetId = supObjetId;
	}

	@Column(name = "SUP_TYPE", nullable = false, length = 20)
	public String getSupType() {
		return this.supType;
	}

	public void setSupType(String supType) {
		this.supType = supType;
	}

	@Column(name = "SUP_DUREE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getSupDuree() {
		return this.supDuree;
	}

	public void setSupDuree(BigDecimal supDuree) {
		this.supDuree = supDuree;
	}

	@Column(name = "SUP_OBJET_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getSupObjetId() {
		return this.supObjetId;
	}

	public void setSupObjetId(BigDecimal supObjetId) {
		this.supObjetId = supObjetId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TSupportmediaId))
			return false;
		TSupportmediaId castOther = (TSupportmediaId) other;

		return ((this.getSupType() == castOther.getSupType()) || (this.getSupType() != null
				&& castOther.getSupType() != null && this.getSupType().equals(castOther.getSupType())))
				&& ((this.getSupDuree() == castOther.getSupDuree()) || (this.getSupDuree() != null
						&& castOther.getSupDuree() != null && this.getSupDuree().equals(castOther.getSupDuree())))
				&& ((this.getSupObjetId() == castOther.getSupObjetId())
						|| (this.getSupObjetId() != null && castOther.getSupObjetId() != null
								&& this.getSupObjetId().equals(castOther.getSupObjetId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSupType() == null ? 0 : this.getSupType().hashCode());
		result = 37 * result + (getSupDuree() == null ? 0 : this.getSupDuree().hashCode());
		result = 37 * result + (getSupObjetId() == null ? 0 : this.getSupObjetId().hashCode());
		return result;
	}

}
