package com.projetBMDrive.entities;
// Generated 14 juin 2021 � 17:47:08 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TSupportmedia generated by hbm2java
 */
@Entity
@Table(name = "T_SUPPORTMEDIA", schema = "BMDRIVE")
public class TSupportmedia implements java.io.Serializable {

	private BigDecimal supId;
	private TArticle TArticle;
	private String supType;
	private BigDecimal supDuree;

	public TSupportmedia() {
	}

	public TSupportmedia(BigDecimal supId, String supType) {
		this.supId = supId;
		this.supType = supType;
	}

	public TSupportmedia(BigDecimal supId, TArticle TArticle, String supType, BigDecimal supDuree) {
		this.supId = supId;
		this.TArticle = TArticle;
		this.supType = supType;
		this.supDuree = supDuree;
	}

	@Id
	@SequenceGenerator(name="T_SUPPORTMEDIA_SEQ", sequenceName = "T_SUPPORTMEDIA_SEQ", allocationSize = 1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="T_SUPPORTMEDIA_SEQ")
	@Column(name = "SUP_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getSupId() {
		return this.supId;
	}

	public void setSupId(BigDecimal supId) {
		this.supId = supId;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUP_ARTICLE_ID")
	public TArticle getTArticle() {
		return this.TArticle;
	}

	public void setTArticle(TArticle TArticle) {
		this.TArticle = TArticle;
	}

	@Column(name = "SUP_TYPE", nullable = false, length = 20)
	public String getSupType() {
		return this.supType;
	}

	public void setSupType(String supType) {
		this.supType = supType;
	}

	@Column(name = "SUP_DUREE", precision = 22, scale = 0)
	public BigDecimal getSupDuree() {
		return this.supDuree;
	}

	public void setSupDuree(BigDecimal supDuree) {
		this.supDuree = supDuree;
	}

}
