package com.projetBMDrive.entities;
// Generated 14 juin 2021 � 17:47:08 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TVisiteur generated by hbm2java
 */
@Entity
@Table(name = "T_VISITEUR", schema = "BMDRIVE")
public class TVisiteur implements java.io.Serializable {

	private BigDecimal visId;
	private TIdentite TIdentite;
	private TPanier TPanier;

	public TVisiteur() {
	}

	public TVisiteur(BigDecimal visId) {
		this.visId = visId;
	}

	public TVisiteur(BigDecimal visId, TIdentite TIdentite, TPanier TPanier) {
		this.visId = visId;
		this.TIdentite = TIdentite;
		this.TPanier = TPanier;
	}

	@Id
	@SequenceGenerator(name="T_VISITEUR_SEQ", sequenceName = "T_VISITEUR_SEQ", allocationSize = 1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="T_VISITEUR_SEQ")
	@Column(name = "VIS_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getVisId() {
		return this.visId;
	}

	public void setVisId(BigDecimal visId) {
		this.visId = visId;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VIS_ID_IDENTITE")
	public TIdentite getTIdentite() {
		return this.TIdentite;
	}

	public void setTIdentite(TIdentite TIdentite) {
		this.TIdentite = TIdentite;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VIS_ID_PANIER")
	public TPanier getTPanier() {
		return this.TPanier;
	}

	public void setTPanier(TPanier TPanier) {
		this.TPanier = TPanier;
	}

}
