package com.projetBMDrive.entities;
// Generated 8 juin 2021 � 11:44:16 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TVisiteur generated by hbm2java
 */
@Entity
@Table(name = "T_VISITEUR", schema = "BMDRIVE")
public class TVisiteur implements java.io.Serializable {

	private BigDecimal visIdVisiteur;
	private TIdentite TIdentite;
	private TPanier TPanier;

	public TVisiteur() {
	}

	public TVisiteur(BigDecimal visIdVisiteur, TIdentite TIdentite, TPanier TPanier) {
		this.visIdVisiteur = visIdVisiteur;
		this.TIdentite = TIdentite;
		this.TPanier = TPanier;
	}

	@Id

	@Column(name = "VIS_ID_VISITEUR", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getVisIdVisiteur() {
		return this.visIdVisiteur;
	}

	public void setVisIdVisiteur(BigDecimal visIdVisiteur) {
		this.visIdVisiteur = visIdVisiteur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VIS_ID_IDENTITE", nullable = false)
	public TIdentite getTIdentite() {
		return this.TIdentite;
	}

	public void setTIdentite(TIdentite TIdentite) {
		this.TIdentite = TIdentite;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VIS_ID_PANIER", nullable = false)
	public TPanier getTPanier() {
		return this.TPanier;
	}

	public void setTPanier(TPanier TPanier) {
		this.TPanier = TPanier;
	}

}
